apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mongo/mongocfg1
    server: 10.10.10.10

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongocfg1
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongocfg2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongocfg3
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh1-1
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh1-2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh1-3
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongos1
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongos2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
