apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongos1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongos1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongos1
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongos1
  labels:
    run: mongos1
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongos1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongos1
  serviceName: mongos1
  template:
    metadata:
      labels:
        name: mongos1
        run: mongos1
    spec:
      restartPolicy: Always
      hostname: mongos1
      containers:
        - image: mongo:latest
          name: mongos1
          ports:
            - name: mongos1
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongos1
              mountPath: /data/db
          command: ["mongos"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          args: ["--configdb", "cfgrs/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
      volumes:
        - name: mongos1
          persistentVolumeClaim:
            claimName: mongos1
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongos2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongos2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongos2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongos2
  labels:
    run: mongos2
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongos2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongos2
  serviceName: mongos2
  template:
    metadata:
      labels:
        name: mongos2
        run: mongos2
    spec:
      restartPolicy: Always
      hostname: mongos2
      containers:
        - image: mongo:latest
          name: mongos2
          ports:
            - name: mongos2
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongos2
              mountPath: /data/db
          command: ["mongos"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          args: ["--configdb", "cfgrs/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
      volumes:
        - name: mongos2
          persistentVolumeClaim:
            claimName: mongos2
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongos3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongos3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongos3
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongos3
  labels:
    run: mongos3
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongos3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongos3
  serviceName: mongos3
  template:
    metadata:
      labels:
        name: mongos3
        run: mongos3
    spec:
      restartPolicy: Always
      hostname: mongos1
      containers:
        - image: mongo:latest
          name: mongos3
          ports:
            - name: mongos3
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongos3
              mountPath: /data/db
          command: ["mongos"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          args: ["--configdb", "cfgrs/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
      volumes:
        - name: mongos3
          persistentVolumeClaim:
            claimName: mongos3
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256