apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh4-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongosh4-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh4-1
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-1
  labels:
    run: mongosh4-1
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongosh4-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongosh4-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongosh4-1
  serviceName: mongosh4-1
  template:
    metadata:
      labels:
        name: mongosh4-1
        run: mongosh4-1
    spec:
      restartPolicy: Always
      hostname: mongosh4-1
      containers:
        - image: mongo:6.0.2
          name: mongosh4-1
          ports:
            - name: mongosh4-1
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongosh4-1
              mountPath: /data/db
          command: ["mongod"]
          args: ["--shardsvr", "--replSet", "rs4", "--dbpath", "/data/db", "--port", "27017", "--auth", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      volumes:
        - name: mongosh4-1
          persistentVolumeClaim:
            claimName: mongosh4-1
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh4-2
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongosh4-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh4-2
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-2
  labels:
    run: mongosh4-2
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongosh4-2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongosh4-2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongosh4-2
  serviceName: mongosh4-2
  template:
    metadata:
      labels:
        name: mongosh4-2
        run: mongosh4-2
    spec:
      restartPolicy: Always
      hostname: mongosh4-2
      containers:
        - image: mongo:6.0.2
          name: mongosh4-2
          ports:
            - name: mongosh4-2
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongosh4-2
              mountPath: /data/db
          command: ["mongod"]
          args: ["--shardsvr", "--replSet", "rs4", "--dbpath", "/data/db", "--port", "27017", "--auth", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      volumes:
        - name: mongosh4-2
          persistentVolumeClaim:
            claimName: mongosh4-2
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh4-3
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mongodb/mongosh4-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernete.worker4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh4-3
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce # only allow one node can be read and write
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-3
  labels:
    run: mongosh4-3
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    run: mongosh4-3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongosh4-3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongosh4-3
  serviceName: mongosh4-3
  template:
    metadata:
      labels:
        name: mongosh4-3
        run: mongosh4-3
    spec:
      restartPolicy: Always
      hostname: mongosh4-3
      containers:
        - image: mongo:6.0.2
          name: mongosh4-3
          ports:
            - name: mongosh4-3
              containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/mongodb/security
            - name: mongosh4-3
              mountPath: /data/db
          command: ["mongod"]
          args: ["--shardsvr", "--replSet", "rs4", "--dbpath", "/data/db", "--port", "27017", "--auth", "--keyFile", "/etc/mongodb/security/mongodb.key", "--bind_ip_all"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      volumes:
        - name: mongosh4-3
          persistentVolumeClaim:
            claimName: mongosh4-3
        - name: secrets-volume
          secret:
            secretName: mongodb.key
            defaultMode: 256